vich_uploader:
    db_driver: orm

    mappings:
        profile_image:
           uri_prefix: /images/profiles
           upload_destination: '%kernel.project_dir%/public/images/profiles'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer   
        post_image:
           uri_prefix: /images/posts
           upload_destination: '%kernel.project_dir%/public/images/posts'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
